# Generated by Django 3.1.6 on 2021-02-18 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='todo_name',
            field=models.TextField(default=''),
        ),
    ]
