# Generated by Django 3.1.6 on 2021-02-18 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_todo_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='todo_name',
        ),
    ]
